### ISSUE TITLE
How to return color value on onChangeEnd?

### ISSUE THREAD

**Issue by 0100101101001011** [itome/flutter_circle_color_picker#13]
Awesome project! I want to use it for sending one end color. Right now it returns the value on dragging, is there a way to make it only returns a value when the drag finished(onPanEnd)? Thank you!

```
class _ColorPicker extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: CircleColorPicker(
        initialColor: Colors.blue,
        onChanged: (color) => print(color),
        size: const Size(300, 300),
        strokeWidth: 8,
        thumbSize: 35,
        textStyle: TextStyle(fontSize: 0),
      ),
    );
  }
}
```

**Comment by nicolasvahidzein** [comment]
I second this option, thanks

**Comment by prabha024** [comment]
@0100101101001011 Did you find any way to solve this?

**Comment by itome** [comment]
@0100101101001011 @prabha024 I added `onEnded` callback. See ↓

https://github.com/itome/flutter_circle_color_picker/commit/be8b3606e6934b2b7f7f619166386ff3bae04cca
