### ISSUE TITLE
Initial Color not being used

### ISSUE THREAD

**Issue by johnwiese-ms** [itome/flutter_circle_color_picker#2]
Here is some code and a screen shot showing by usage.  You can see in the picture that the container I put on the page is filled with the same value that I've set the intialColor value to but the control is not showing the color that was set.

```
 Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                Text(
                  'Away Color',
                  style: TextStyle(
                    fontSize: 20.0,
                    fontWeight: FontWeight.bold,
                  )
                ),
                CircleColorPicker(
                  initialColor: awayPickerColor,
                  onChanged: (color) => changeAwayColor(color),
                  size: const Size(240, 240),
                  strokeWidth: 4,
                  thumbSize: 36,
                ),
                Container(width:100, height:20, color: awayPickerColor),
              ]
            ),
```
![image](https://user-images.githubusercontent.com/54288891/72542419-bd6c9780-3849-11ea-953c-10d90c47b707.png)

**Comment by itome** [comment]
Thank you for your reporting.
I think this is expected behavior. The controller thumb color is hue and the color of center circle is hue + lightness, so there color are not always same.

This color picker is inspired by https://github.com/joncardasis/ChromaColorPicker and the library works same as this.

**Comment by itome** [comment]
I close this issue, please feel free to reopen if you have some question 👍
