### ISSUE TITLE
Request: Option for custom text

### ISSUE THREAD

**Issue by S-Man42** [itome/flutter_circle_color_picker#5]
Currently the color picker text shows the hex value of the chosen color, which, indeed, is a very useful default. But it would be great to get the possibility to change (maybe for showing RGB or HSL values) or even remove this text. Furthermore, with a custom text you could add a custom TextStyle for better app integration.

Is is this possible yet? Or is there a chance to add a text attribute?

**Comment by itome** [comment]
https://github.com/itome/flutter_circle_color_picker/pull/3 ← This PR may helps you to change text style.

I have two options to archive your requirement.

1. Add `showColorCode` flag to hide color code text. This allows you to hide text in the circle and show RGB or HSL color code text outside (by handling `onChanged` callback).
2. Add `String Function(Color) textBuilder` parameter to change text in the circle.

I have little hesitate that the color picker design collapsed by the second option. For example, very long text may protrude from circle.

@S-Man42 Which do you like from the library user's point of view?

**Comment by S-Man42** [comment]
Yes, I saw this PR afterwards. :D

Hm, I understand your thoughts. But nevertheless I would tend to second option. I believe the user should handle this on its own. On the other hand you provide a great flexibility with that option. In a case of overflow, the user can wrap or shrink the text by himself.

**Comment by itome** [comment]
https://github.com/itome/flutter_circle_color_picker/pull/7

I created PR. Is this fit your usage?

**Comment by S-Man42** [comment]
I'll check it out tomorrow, but the first view looks great! Thank you!

**Comment by itome** [comment]
Close due to https://github.com/itome/flutter_circle_color_picker/pull/7 was merged.
