### ISSUE TITLE
pub.dev is still 0.1.1

### ISSUE THREAD

**Issue by stefandevo** [itome/flutter_circle_color_picker#9]
I have seen some commits about customizing textStyle etc but this is not yet on pub.dev.
Any news?

**Comment by sgehrman** [comment]
yeah, still old. I was wondering why the source code has more features than the release.

**Comment by itome** [comment]
Sorry for being late. Today https://pub.dev/packages/flutter_circle_color_picker/versions/0.2.0 is released.
